global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          source: 'otel-collector'

  - job_name: 'cockroachdb'
    scrape_interval: 10s
    static_configs:
      - targets: ['cockroachdb:8080']
        labels:
          database: 'cockroachdb'

